### PR TITLE
Italian language file

### PR DESCRIPTION
**Pull request by jeckodevelopment**
Italian language for the plugin.

### CODE REVIEW

**Comment by zero-24** [comment]
thanks @jeckodevelopment I have just changed the base branch as the branch is going to be released soon. Can you update your translation to match: https://github.com/zero-24/plg_system_httpheader/tree/saveToServerConfigFile/language/en-GB ?

**Comment by jeckodevelopment** [comment]
@zero-24 should be ok now :)

**Comment by zero-24** [comment]
thanks merging.

**Comment by jeckodevelopment** [comment]
Thank you!

**Pull request merged**
