### PR TITLE
Check if Document has getHeadData method

### PR DESCRIPTION
**Pull request by SniperSister**
Fixes i.e. JsonDocument calls

### CODE REVIEW

**Comment by zero-24** [comment]
hmm shloud't we skip any processing in case we are not running on an html site? As csp is only relevant there right?

**Comment by SniperSister** [comment]
Indeed

**Comment by zero-24** [comment]
Release is out thanks @SniperSister : https://github.com/zero-24/plg_system_httpheader/releases/tag/1.0.8

**Comment by zero-24** [comment]
Other issue has been moved to: https://github.com/zero-24/plg_system_httpheader/issues/19

**Pull request merged**
